### ISSUE TITLE
black boxes in my browser which are unreadable and annoying 

### ISSUE THREAD

**Issue by wildgamharsh** [MishaProductions/Rectify11Installer#174] opened 2023-06-21 06:11 UTC
### Description

i installed rectify 11 with dark mica theme and now my browsers are having dark dropdown menus which dont look good

### Steps To Reproduce

fix the black dropdown menus or add white text in them 

### Rectify11 Version

rp3 

### Windows Version

windows 11 22h2 

### Logs

no log

**Comment by xverge** [comment] 2023-06-25 18:26
Duplicate of #127, there's a fix on the issue page

**Closed** 2023-07-11 17:37 UTC
Labels: bug

**Comment by ulao** [comment] 2023-10-21 03:18
I was told in the discord that this is known, and some how the files AccentColorizer and AccentColorizer-E11 fix this. Though it does not seem to do anything for me. There was some talk that disabling HDR helped too but that also does not work for me.
