### ISSUE TITLE
Cannot uninstall

### ISSUE THREAD

**Issue by celsiusqc** [MishaProductions/Rectify11Installer#178] opened 2023-06-29 01:33 UTC
### Description

I cannot uninstall the program nor undo the changes made by it.

### Steps To Reproduce

install the program, then try and install it

### Rectify11 Version

3.0

### Windows Version

22621.1928

### Logs

none

**Comment by Typical0** [comment] 2023-06-29 08:46
Duplicate of #99

**Closed** 2023-07-11 17:35 UTC
Labels: bug
