### ISSUE TITLE
No Rectify11 Settings, Color Bugs, Uninstall dont work

### ISSUE THREAD

**Issue by NightRain86** [MishaProductions/Rectify11Installer#158] opened 2023-05-28 09:48 UTC
I've installed the last Version of Rectify 11. From now on, I cannot do anything with Rectify because there are no Settings for it. Many Windows have Color Bugs (they are black inside). I wanted to deinstall Rectify but the Button don't work (it does nothing when I click on it)

My Windows Restore Point don't work. So, to fix this I must reinstall Windows?

**Comment by RTFTR** [comment] 2023-05-28 09:52
The only way to uninstall is:
1. You do sfc /scannow to remove all the modified icons and replace the original one
2. Find Themetool.exe(C:\Windows or find it in github) and run it as an administrator
3. Select and Apply "Windows (Dark)"
4. Uninstall extras that you installed with Rectify11

**Comment by Typical0** [comment] 2023-05-28 09:54
1. Rectify11 Control Center was disabled
2. If you've chosen Dark theme, then it's expected to be black
3. Just use Win+R, type in "themetool", select Windows (dark) and press Apply

**Comment by evansidhu** [comment] 2023-05-29 20:45
Run system restore from the windows recovery environnment, fixed it for me.

**Comment by MishaProductions** [comment] 2023-05-31 14:51
Duplicate of https://github.com/MishaProductions/Rectify11Installer/issues/99 https://github.com/MishaProductions/Rectify11Installer/issues/94 https://github.com/MishaProductions/Rectify11Installer/issues/89 https://github.com/MishaProductions/Rectify11Installer/issues/71 https://github.com/MishaProductions/Rectify11Installer/issues/71 https://github.com/MishaProductions/Rectify11Installer/issues/149

**Closed by MishaProductions** 2023-05-31 14:51 UTC
