### ISSUE TITLE
wont uninstall with mine either

### ISSUE THREAD

**Issue by Snasdagamer** [MishaProductions/Rectify11Installer#161] opened 2023-05-31 14:35 UTC
I am also unable to uninstall using RP3.  Clicking the uninstall button does **NOTHING**.

_Originally posted by @PwrSrg in https://github.com/MishaProductions/Rectify11Installer/issues/71#issuecomment-1430139315_

**Comment by MishaProductions** [comment] 2023-05-31 14:50
Duplicate of https://github.com/MishaProductions/Rectify11Installer/issues/99 https://github.com/MishaProductions/Rectify11Installer/issues/94 https://github.com/MishaProductions/Rectify11Installer/issues/89 https://github.com/MishaProductions/Rectify11Installer/issues/71 https://github.com/MishaProductions/Rectify11Installer/issues/71 #149

**Closed by MishaProductions** 2023-05-31 14:50 UTC

**Comment by evansidhu** [comment] 2023-05-31 19:35
Do you have a system restore point, if yes then use it via the windows recovery environment to uninstall
